---
driver:
  name: docker

provisioner:
  name: shell
  data_path: ./
  script: ./test/bootstrap.sh

platforms:
  - name: centos-6
    driver:
  - name: centos-7.1
    driver:
      privileged: true
      run_command: /sbin/init

suites:
  - name: pre-build
    provisioner:
      script: ./test/scripts/pre-build.sh

  - name: pre-build_consul_acl
    provisioner:
      script: ./test/scripts/pre-build-acl.sh

  - name: pre-configure
    provisioner:
      script: ./test/scripts/pre-configure.sh

  - name: pre-configure_consul_acl
    provisioner:
      script: ./test/scripts/pre-configure-acl.sh

  - name: pre-configure_optional
    provisioner:
      script: ./test/scripts/pre-configure-optional.sh
