---
driver:
  name: docker

provisioner:
  name: shell
  data_path: ./
  script: ./test/bootstrap.sh

platforms:
  - name: centos-6
    driver:
  - name: centos-7.1
    driver:
      privileged: true
      run_command: /sbin/init

suites:
  - name: pre-build
    provisioner:
      script: ./test/scripts/pre-build.sh

  - name: pre-build_consul_acl
    run_list:
      - ./bin/init.sh
    attributes:
      cc_pattern: tomcat_pattern
      cc_revision: develop
      cc_role: ap
      cc_token: UWHlGY3fjIqpcDxZdVC4yw==

  - name: pre-configure
    run_list:
      - ./bin/init.sh
      - ./test/bin/pre_configure.sh
    attributes:
      cc_pattern: tomcat_pattern
      cc_revision: develop
      cc_role: db
      cc_token:

  - name: pre-configure_consul_acl
    run_list:
      - ./bin/init.sh
      - ./test/bin/pre_configure.sh
    attributes:
      cc_pattern: tomcat_cluster_pattern
      cc_revision: develop
      cc_role: web,ap
      cc_token: UWHlGY3fjIqpcDxZdVC4yw==

  - name: pre-configure_optional
    run_list:
      - ./bin/init.sh
      - ./test/bin/set_attributes.sh
      - ./test/bin/pre_configure.sh
    attributes:
      cc_pattern: tomcat_pattern
      cc_revision: develop
      cc_role: db
      cc_token: UWHlGY3fjIqpcDxZdVC4yw==
